### ISSUE TITLE
XYB Jpegli

### ISSUE THREAD

**Issue by kremzli** [awxkee/aire#3]
Add an option for converting to XYB too. I tested it yesterday (with cjpegli --xyb) and it shaved off another 4% without any quality loss (other than a little bit you wont ever notice without pixel peeping)

Related:
https://github.com/T8RIN/ImageToolbox/issues/920

**Comment by awxkee** [comment]
I'm a little sceptical about XYB feature in android. It works on behalf of ICC profiles and the most of android devs even have no idea what is it, even android itself just started support ICC profiles only from API 34+ (even not all famous software properly handle ICC profiles all the times). I think it is not really needed for real `end user` especially with really high chance that part of software will not support ICC profile and when it will that 4% compressed will cost twice / or triple decoding time due to quite slow implementation of rendering ICC.
So between a choice of generation potentially slow jpegs or perhaps invalid rendering I'd like to avoid any features that have a bounds to ICC.

**Comment by awxkee** [comment]
So the question is: Is it really 4% worth 100-200%+ rendering speed decrease, and highly likely invalid rendering on some software? As to me it is not sounds as a really good trade-off

**Comment by kremzli** [comment]
Didnt know it just used ICC, so yeah you can ignore this if you wish to not deal with that and android doesnt like it

**Comment by awxkee** [comment]
Yeah, the whole idea of `XYB` if to use ICC. The image info saved in XYB colorspace instead of more traditional YUV, CMYK or RGB and use ICC as `transfer function` between the XYB and RGB. That means ICC not `should be` handled but `must be` handled.

That is not only android. ICC in full support properly done very rear.

**Comment by awxkee** [comment]
So if you unsure that software that will use images with ICC will handle it better avoid this one.

And I'm not sure.
